/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Section {
    title: string;
    description?: string;
    image?: ExternalBlob;
    subtitle?: string;
}
export interface WebsiteContent {
    sections: Array<Section>;
    gallery: Array<GalleryImage>;
}
export interface GalleryImage {
    id: string;
    title: string;
    description: string;
    imageUrl: ExternalBlob;
}
export interface UserProfile {
    name: string;
    email: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    addGalleryImage(id: number, image: GalleryImage): Promise<void>;
    addSection(sectionId: string, section: Section): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteGalleryImage(id: number): Promise<void>;
    deleteSection(sectionId: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGalleryImageCount(): Promise<bigint>;
    getSectionCount(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    /**
     * / CONTENT MANAGEMENT
     */
    getWebsiteContent(): Promise<WebsiteContent>;
    /**
     * / AUTHENTICATION & AUTHORIZATION
     */
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateGalleryImage(id: number, image: GalleryImage): Promise<void>;
    updateSection(sectionId: string, section: Section): Promise<void>;
    updateWebsiteContent(content: WebsiteContent): Promise<void>;
    uploadImage(image: ExternalBlob): Promise<ExternalBlob>;
}
import type { ExternalBlob as _ExternalBlob, GalleryImage as _GalleryImage, Section as _Section, UserProfile as _UserProfile, UserRole as _UserRole, WebsiteContent as _WebsiteContent } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async addGalleryImage(arg0: number, arg1: GalleryImage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryImage(arg0, await to_candid_GalleryImage_n1(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryImage(arg0, await to_candid_GalleryImage_n1(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async addSection(arg0: string, arg1: Section): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSection(arg0, await to_candid_Section_n4(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSection(arg0, await to_candid_Section_n4(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async deleteGalleryImage(arg0: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryImage(arg0);
            return result;
        }
    }
    async deleteSection(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSection(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSection(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this.uploadFile, this.downloadFile, result);
        }
    }
    async getGalleryImageCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryImageCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryImageCount();
            return result;
        }
    }
    async getSectionCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getSectionCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSectionCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this.uploadFile, this.downloadFile, result);
        }
    }
    async getWebsiteContent(): Promise<WebsiteContent> {
        if (this.processError) {
            try {
                const result = await this.actor.getWebsiteContent();
                return from_candid_WebsiteContent_n11(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWebsiteContent();
            return from_candid_WebsiteContent_n11(this.uploadFile, this.downloadFile, result);
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateGalleryImage(arg0: number, arg1: GalleryImage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGalleryImage(arg0, await to_candid_GalleryImage_n1(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGalleryImage(arg0, await to_candid_GalleryImage_n1(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async updateSection(arg0: string, arg1: Section): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSection(arg0, await to_candid_Section_n4(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSection(arg0, await to_candid_Section_n4(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async updateWebsiteContent(arg0: WebsiteContent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWebsiteContent(await to_candid_WebsiteContent_n22(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWebsiteContent(await to_candid_WebsiteContent_n22(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async uploadImage(arg0: ExternalBlob): Promise<ExternalBlob> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadImage(await to_candid_ExternalBlob_n3(this.uploadFile, this.downloadFile, arg0));
                return from_candid_ExternalBlob_n18(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadImage(await to_candid_ExternalBlob_n3(this.uploadFile, this.downloadFile, arg0));
            return from_candid_ExternalBlob_n18(this.uploadFile, this.downloadFile, result);
        }
    }
}
async function from_candid_ExternalBlob_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await downloadFile(value);
}
async function from_candid_GalleryImage_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryImage): Promise<GalleryImage> {
    return await from_candid_record_n21(uploadFile, downloadFile, value);
}
async function from_candid_Section_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Section): Promise<Section> {
    return await from_candid_record_n15(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n10(uploadFile, downloadFile, value);
}
async function from_candid_WebsiteContent_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WebsiteContent): Promise<WebsiteContent> {
    return await from_candid_record_n12(uploadFile, downloadFile, value);
}
function from_candid_opt_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n18(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sections: Array<_Section>;
    gallery: Array<_GalleryImage>;
}): Promise<{
    sections: Array<Section>;
    gallery: Array<GalleryImage>;
}> {
    return {
        sections: await from_candid_vec_n13(uploadFile, downloadFile, value.sections),
        gallery: await from_candid_vec_n19(uploadFile, downloadFile, value.gallery)
    };
}
async function from_candid_record_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: [] | [string];
    image: [] | [_ExternalBlob];
    subtitle: [] | [string];
}): Promise<{
    title: string;
    description?: string;
    image?: ExternalBlob;
    subtitle?: string;
}> {
    return {
        title: value.title,
        description: record_opt_to_undefined(from_candid_opt_n16(uploadFile, downloadFile, value.description)),
        image: record_opt_to_undefined(await from_candid_opt_n17(uploadFile, downloadFile, value.image)),
        subtitle: record_opt_to_undefined(from_candid_opt_n16(uploadFile, downloadFile, value.subtitle))
    };
}
async function from_candid_record_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    description: string;
    imageUrl: _ExternalBlob;
}): Promise<{
    id: string;
    title: string;
    description: string;
    imageUrl: ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        imageUrl: await from_candid_ExternalBlob_n18(uploadFile, downloadFile, value.imageUrl)
    };
}
function from_candid_variant_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Section>): Promise<Array<Section>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Section_n14(uploadFile, downloadFile, x)));
}
async function from_candid_vec_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryImage>): Promise<Array<GalleryImage>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GalleryImage_n20(uploadFile, downloadFile, x)));
}
async function to_candid_ExternalBlob_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await uploadFile(value);
}
async function to_candid_GalleryImage_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GalleryImage): Promise<_GalleryImage> {
    return await to_candid_record_n2(uploadFile, downloadFile, value);
}
async function to_candid_Section_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Section): Promise<_Section> {
    return await to_candid_record_n5(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n7(uploadFile, downloadFile, value);
}
async function to_candid_WebsiteContent_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WebsiteContent): Promise<_WebsiteContent> {
    return await to_candid_record_n23(uploadFile, downloadFile, value);
}
async function to_candid_record_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    description: string;
    imageUrl: ExternalBlob;
}): Promise<{
    id: string;
    title: string;
    description: string;
    imageUrl: _ExternalBlob;
}> {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        imageUrl: await to_candid_ExternalBlob_n3(uploadFile, downloadFile, value.imageUrl)
    };
}
async function to_candid_record_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sections: Array<Section>;
    gallery: Array<GalleryImage>;
}): Promise<{
    sections: Array<_Section>;
    gallery: Array<_GalleryImage>;
}> {
    return {
        sections: await to_candid_vec_n24(uploadFile, downloadFile, value.sections),
        gallery: await to_candid_vec_n25(uploadFile, downloadFile, value.gallery)
    };
}
async function to_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description?: string;
    image?: ExternalBlob;
    subtitle?: string;
}): Promise<{
    title: string;
    description: [] | [string];
    image: [] | [_ExternalBlob];
    subtitle: [] | [string];
}> {
    return {
        title: value.title,
        description: value.description ? candid_some(value.description) : candid_none(),
        image: value.image ? candid_some(await to_candid_ExternalBlob_n3(uploadFile, downloadFile, value.image)) : candid_none(),
        subtitle: value.subtitle ? candid_some(value.subtitle) : candid_none()
    };
}
function to_candid_variant_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Section>): Promise<Array<_Section>> {
    return await Promise.all(value.map(async (x)=>await to_candid_Section_n4(uploadFile, downloadFile, x)));
}
async function to_candid_vec_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<GalleryImage>): Promise<Array<_GalleryImage>> {
    return await Promise.all(value.map(async (x)=>await to_candid_GalleryImage_n1(uploadFile, downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
