/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GalleryImage = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : ExternalBlob,
});
export const Section = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'image' : IDL.Opt(ExternalBlob),
  'subtitle' : IDL.Opt(IDL.Text),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const WebsiteContent = IDL.Record({
  'sections' : IDL.Vec(Section),
  'gallery' : IDL.Vec(GalleryImage),
});

export const idlService = IDL.Service({
  'addGalleryImage' : IDL.Func([IDL.Nat32, GalleryImage], [], []),
  'addSection' : IDL.Func([IDL.Text, Section], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteGalleryImage' : IDL.Func([IDL.Nat32], [], []),
  'deleteSection' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGalleryImageCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getSectionCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWebsiteContent' : IDL.Func([], [WebsiteContent], ['query']),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateGalleryImage' : IDL.Func([IDL.Nat32, GalleryImage], [], []),
  'updateSection' : IDL.Func([IDL.Text, Section], [], []),
  'updateWebsiteContent' : IDL.Func([WebsiteContent], [], []),
  'uploadImage' : IDL.Func([ExternalBlob], [ExternalBlob], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GalleryImage = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : ExternalBlob,
  });
  const Section = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'image' : IDL.Opt(ExternalBlob),
    'subtitle' : IDL.Opt(IDL.Text),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const WebsiteContent = IDL.Record({
    'sections' : IDL.Vec(Section),
    'gallery' : IDL.Vec(GalleryImage),
  });
  
  return IDL.Service({
    'addGalleryImage' : IDL.Func([IDL.Nat32, GalleryImage], [], []),
    'addSection' : IDL.Func([IDL.Text, Section], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteGalleryImage' : IDL.Func([IDL.Nat32], [], []),
    'deleteSection' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGalleryImageCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getSectionCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWebsiteContent' : IDL.Func([], [WebsiteContent], ['query']),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateGalleryImage' : IDL.Func([IDL.Nat32, GalleryImage], [], []),
    'updateSection' : IDL.Func([IDL.Text, Section], [], []),
    'updateWebsiteContent' : IDL.Func([WebsiteContent], [], []),
    'uploadImage' : IDL.Func([ExternalBlob], [ExternalBlob], []),
  });
};

export const init = ({ IDL }) => { return []; };